# Generated by Django 2.2.2 on 2019-06-05 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='strat_time',
            new_name='start_time',
        ),
    ]
