# Generated by Django 2.1.9 on 2019-06-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20190605_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('parent_id', models.CharField(max_length=4, verbose_name='归属条线')),
                ('project_type', models.CharField(max_length=4, verbose_name='项目类型')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
