# Generated by Django 2.1.9 on 2019-06-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_projectinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='validate_state',
            field=models.CharField(default='1', max_length=1, verbose_name='数据有效性'),
        ),
    ]
