# Generated by Django 2.1.9 on 2019-06-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_projectinfo_validate_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='validate_state',
            field=models.BooleanField(),
        ),
    ]
