# Generated by Django 2.1.9 on 2019-06-19 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_interfaceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.CharField(max_length=100, verbose_name='接口字段')),
                ('field_name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('type', models.CharField(max_length=100, verbose_name='数据类型')),
                ('length', models.IntegerField(verbose_name='字段长度')),
                ('belong_list', models.CharField(max_length=40, verbose_name='归属LIST')),
                ('belong_dict', models.CharField(max_length=40, verbose_name='归属DICT')),
                ('dependent_field', models.CharField(max_length=40, verbose_name='依赖字段')),
                ('dependent_value', models.CharField(max_length=40, verbose_name='依赖值')),
                ('is_null', models.BooleanField(verbose_name='是否可空')),
                ('default_value', models.CharField(max_length=100, verbose_name='默认值')),
                ('remarks', models.CharField(max_length=2000, verbose_name='备注')),
                ('validate_state', models.BooleanField(verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='validate_state',
            field=models.BooleanField(verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='interfacefield',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.InterfaceInfo'),
        ),
    ]
