# Generated by Django 2.1.9 on 2019-06-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20190619_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacefield',
            name='belong_dict',
            field=models.CharField(blank=True, max_length=40, verbose_name='归属DICT'),
        ),
        migrations.AlterField(
            model_name='interfacefield',
            name='belong_list',
            field=models.CharField(blank=True, max_length=40, verbose_name='归属LIST'),
        ),
        migrations.AlterField(
            model_name='interfacefield',
            name='default_value',
            field=models.CharField(blank=True, max_length=100, verbose_name='默认值'),
        ),
        migrations.AlterField(
            model_name='interfacefield',
            name='dependent_field',
            field=models.CharField(blank=True, max_length=40, verbose_name='依赖字段'),
        ),
        migrations.AlterField(
            model_name='interfacefield',
            name='dependent_value',
            field=models.CharField(blank=True, max_length=40, verbose_name='依赖值'),
        ),
        migrations.AlterField(
            model_name='interfacefield',
            name='length',
            field=models.IntegerField(blank=True, verbose_name='字段长度'),
        ),
        migrations.AlterField(
            model_name='interfacefield',
            name='remarks',
            field=models.CharField(blank=True, max_length=2000, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='headers_content_two',
            field=models.CharField(blank=True, max_length=1000, verbose_name='请求报文头内容2'),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='headers_label_two',
            field=models.CharField(blank=True, max_length=50, verbose_name='请求报文头标签2'),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='remarks',
            field=models.CharField(blank=True, max_length=2000, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='request_json',
            field=models.CharField(blank=True, max_length=4000, verbose_name='请求报文模板'),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='response_json',
            field=models.CharField(blank=True, max_length=4000, verbose_name='响应报文模板'),
        ),
    ]
