# Generated by Django 2.1.9 on 2019-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_auto_20190619_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceinfo',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, verbose_name='备注'),
        ),
    ]
