# Generated by Django 2.1.9 on 2019-06-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_auto_20190619_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_name', models.CharField(max_length=40, verbose_name='规则名称')),
                ('rules_type', models.CharField(max_length=10, verbose_name='规则类型')),
                ('data_format', models.CharField(max_length=40, verbose_name='数据格式')),
                ('rule_comment', models.CharField(blank=True, max_length=100, verbose_name='规则描述')),
                ('regexp_1', models.CharField(blank=True, max_length=100, verbose_name='正则表达式1')),
                ('regexp_2', models.CharField(blank=True, max_length=100, verbose_name='正则表达式2')),
                ('regexp_3', models.CharField(blank=True, max_length=100, verbose_name='正则表达式3')),
                ('regexp_4', models.CharField(blank=True, max_length=100, verbose_name='正则表达式4')),
                ('regexp_5', models.CharField(blank=True, max_length=100, verbose_name='正则表达式5')),
                ('regexp_6', models.CharField(blank=True, max_length=100, verbose_name='正则表达式6')),
                ('regexp_7', models.CharField(blank=True, max_length=100, verbose_name='正则表达式7')),
                ('regexp_8', models.CharField(blank=True, max_length=100, verbose_name='正则表达式8')),
                ('regexp_9', models.CharField(blank=True, max_length=100, verbose_name='正则表达式9')),
                ('regexp_10', models.CharField(blank=True, max_length=100, verbose_name='正则表达式10')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('validate_state', models.BooleanField(verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
