# Generated by Django 2.1.9 on 2019-06-20 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_publicrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(blank=True, max_length=100, verbose_name='用例名称')),
                ('request_json', models.TextField(blank=True, max_length=4000, verbose_name='请求报文')),
                ('response_json', models.TextField(blank=True, max_length=4000, verbose_name='响应报文')),
                ('version', models.CharField(blank=True, max_length=10, verbose_name='用例版本号')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('validate_state', models.BooleanField(verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.InterfaceField')),
                ('rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.PublicRule')),
            ],
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='request_json',
            field=models.TextField(blank=True, max_length=4000, verbose_name='请求报文模板'),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='response_json',
            field=models.TextField(blank=True, max_length=4000, verbose_name='响应报文模板'),
        ),
    ]
