# Generated by Django 2.1.9 on 2019-06-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_auto_20190620_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_status', models.CharField(blank=True, max_length=2, verbose_name='批次状态')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='执行开始时间')),
                ('finish_time', models.DateTimeField(verbose_name='执行结束时间')),
                ('execute_frequency', models.IntegerField(verbose_name='执行次数')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('validate_state', models.BooleanField(verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
