# Generated by Django 2.1.9 on 2019-06-20 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_batchjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_status', models.CharField(blank=True, max_length=2, verbose_name='用例状态')),
                ('request_json', models.TextField(blank=True, max_length=4000, verbose_name='请求报文')),
                ('response_json', models.TextField(blank=True, max_length=4000, verbose_name='响应报文')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('validate_state', models.BooleanField(verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.BatchJob')),
            ],
        ),
        migrations.AlterField(
            model_name='publiccase',
            name='request_json',
            field=models.TextField(blank=True, max_length=4000, verbose_name='请求报文模板'),
        ),
        migrations.AlterField(
            model_name='publiccase',
            name='response_json',
            field=models.TextField(blank=True, max_length=4000, verbose_name='响应报文模板'),
        ),
        migrations.AddField(
            model_name='batchcase',
            name='public_case_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.PublicCase'),
        ),
    ]
