# Generated by Django 2.1.9 on 2019-06-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_auto_20190620_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='服务器名称')),
                ('server_ip', models.CharField(blank=True, max_length=16, null=True, verbose_name='服务器IP')),
                ('server_port', models.CharField(blank=True, max_length=6, null=True, verbose_name='服务器端口')),
                ('validate_state', models.BooleanField(verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
