# Generated by Django 2.1.9 on 2019-06-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0015_auto_20190625_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchcase',
            name='request_json',
            field=models.TextField(blank=True, verbose_name='请求报文'),
        ),
        migrations.AlterField(
            model_name='batchcase',
            name='response_json',
            field=models.TextField(blank=True, verbose_name='响应报文'),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='request_json',
            field=models.TextField(blank=True, verbose_name='请求报文模板'),
        ),
        migrations.AlterField(
            model_name='interfaceinfo',
            name='response_json',
            field=models.TextField(blank=True, verbose_name='响应报文模板'),
        ),
        migrations.AlterField(
            model_name='publiccase',
            name='request_json',
            field=models.TextField(blank=True, verbose_name='请求报文模板'),
        ),
        migrations.AlterField(
            model_name='publiccase',
            name='response_json',
            field=models.TextField(blank=True, verbose_name='响应报文模板'),
        ),
    ]
