# Generated by Django 2.1.9 on 2019-06-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_auto_20190625_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinfo',
            options={'verbose_name': '项目信息', 'verbose_name_plural': '项目信息'},
        ),
    ]
